// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeEmKqHpIpJijpTrU2tqtrIZOsRLRx8-c',
    appId: '1:993512018843:android:358a1fa5cb70e23884473e',
    messagingSenderId: '993512018843',
    projectId: 'turbopaisa-fa189',
    storageBucket: 'turbopaisa-fa189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-c8b07NI_nVfbckxQ-YfTGnVKq3cOXfw',
    appId: '1:993512018843:ios:c389895194a0883384473e',
    messagingSenderId: '993512018843',
    projectId: 'turbopaisa-fa189',
    storageBucket: 'turbopaisa-fa189.appspot.com',
    iosBundleId: 'com.ramesh.offers.offersapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQLiAEtgE86QmPKan9fXOWUpM1sZsKaE',
    appId: '1:993512018843:web:46d9ef1a9ece8ba484473e',
    messagingSenderId: '993512018843',
    projectId: 'turbopaisa-fa189',
    authDomain: 'turbopaisa-fa189.firebaseapp.com',
    storageBucket: 'turbopaisa-fa189.appspot.com',
    measurementId: 'G-6ZG3S31PV9',
  );

}